name: eco
version: ${projectVersion}
main: com.willfp.eco.internal.spigot.EcoImpl
api-version: 1.19
load: STARTUP

folia-supported: true

dependencies:
  - name: ProtocolLib
    required: false
    bootstrap: false

  - name: WorldGuard
    required: false
    bootstrap: false

  - name: GriefPrevention
    required: false
    bootstrap: false

  - name: Towny
    required: false
    bootstrap: false

  - name: FactionsUUID
    required: false
    bootstrap: false

  - name: Lands
    required: false
    bootstrap: false

  - name: Kingdoms
    required: false
    bootstrap: false

  - name: NoCheatPlus
    required: false
    bootstrap: false

  - name: AAC
    required: false
    bootstrap: false

  - name: Matrix
    required: false
    bootstrap: false

  - name: Spartan
    required: false
    bootstrap: false

  - name: Vulcan
    required: false
    bootstrap: false

  - name: PlaceholderAPI
    required: false
    bootstrap: false

  - name: mcMMO
    required: false
    bootstrap: false

  - name: CombatLogX
    required: false
    bootstrap: false

  - name: ShopGUIPlus
    required: false
    bootstrap: false

  - name: ItemsAdder
    required: false
    bootstrap: false

  - name: Oraxen
    required: false
    bootstrap: false

  - name: HeadDatabase
    required: false
    bootstrap: false

  - name: Multiverse-Inventories
    required: false
    bootstrap: false

  - name: Alice
    required: false
    bootstrap: false

  - name: HolographicDisplays
    required: false
    bootstrap: false

  - name: GHolo
    required: false
    bootstrap: false

  - name: CMI
    required: false
    bootstrap: false

  - name: Essentials
    required: false
    bootstrap: false

  - name: Vault
    required: false
    bootstrap: false

  - name: BentoBox
    required: false
    bootstrap: false

  - name: DeluxeCombat
    required: false
    bootstrap: false

  - name: IridiumSkyblock
    required: false
    bootstrap: false

  - name: SuperiorSkyblock2
    required: false
    bootstrap: false

  - name: FabledSkyBlock
    required: false
    bootstrap: false

  - name: CrashClaim
    required: false
    bootstrap: false

  - name: DecentHolograms
    required: false
    bootstrap: false

  - name: MythicMobs
    required: false
    bootstrap: false

  - name: CustomCrafting
    required: false
    bootstrap: false

  - name: ExecutableItems
    required: false
    bootstrap: false

  - name: RPGHorses
    required: false
    bootstrap: false

  - name: EconomyShopGUI
    required: false
    bootstrap: false

  - name: EconomyShopGUI-Premium
    required: false
    bootstrap: false

  - name: zShop
    required: false
    bootstrap: false

  - name: DeluxeSellwands
    required: false
    bootstrap: false

  - name: Scyther
    required: false
    bootstrap: false

  - name: ModelEngine
    required: false
    bootstrap: false

  - name: PvPManager
    required: false
    bootstrap: false

  - name: DeluxeMenus
    required: false
    bootstrap: false

  - name: UltraEconomy
    required: false
    bootstrap: false

  - name: PlayerPoints
    required: false
    bootstrap: false

  - name: Denizen
    required: false
    bootstrap: false

  - name: RoyaleEconomy
    required: false
    bootstrap: false