name: eco
version: ${projectVersion}
main: com.willfp.eco.spigot.EcoHandler
api-version: 1.16
authors: [Auxilor]
website: willfp.com
loadbefore:
  - EcoEnchants
  - Talismans
  - StatTrackers
  - EcoArmor
  - EcoBosses
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - mcMMO
  - CombatLogX
libraries:
  - org.reflections:reflections:0.9.12
  - org.apache.maven:maven-artifact:3.0.3