name: eco
version: ${projectVersion}
main: com.willfp.eco.internal.spigot.EcoImpl
api-version: 1.21.4
authors: [ Auxilor ]
website: willfp.com
load: STARTUP

# Fixes some plugins breaking load order
loadbefore:
  - Spartan
  - CustomCrafting
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - CMI
  - DeluxeCombat
  - ShopGUIPlus
  - DeluxeMenus
softdepend:
  - ItemBridge
  - HuskClaims
  - HuskTowns
  - Terra
  - ProtocolLib
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Kingdoms
  - AAC
  - Matrix
  - Vulcan
  - PlaceholderAPI
  - mcMMO
  - CombatLogX
  - ItemsAdder
  - Oraxen
  - Nexo
  - HeadDatabase
  - Multiverse-Inventories
  - Alice
  - HolographicDisplays
  - GHolo
  - Essentials
  - Vault
  - BentoBox
  - IridiumSkyblock
  - SuperiorSkyblock2
  - FabledSkyBlock
  - DecentHolograms
  - MythicMobs
  - RPGHorses
  - zShop
  - DeluxeSellwands
  - Scyther
  - ModelEngine
  - PvPManager
  - DeluxeMenus
  - UltraEconomy
  - PlayerPoints
  - Denizen
  - RoyaleEconomy
  - FancyHolograms
  - CraftEngine
  - ExcellentEconomy
  - ExcellentShop

libraries:
  - com.mysql:mysql-connector-j:9.6.0
  - org.mariadb.jdbc:mariadb-java-client:2.7.12
  - com.zaxxer:HikariCP:7.0.2
  - net.kyori:adventure-platform-bukkit:4.4.1
  - org.mongodb:mongodb-driver-kotlin-coroutine:5.6.2
  - io.hotmoka:toml4j:0.7.3
  - net.kyori:adventure-api:5.0.1
  - net.kyori:adventure-text-serializer-gson:5.0.1
  - net.kyori:adventure-text-serializer-legacy:5.0.1
  - com.github.ben-manes.caffeine:caffeine:3.2.3
